steps:
  - label: ":hammmer: Test"
    command:
      - npm install
      - npm run-script buildKiteTest
  - label: ":rocket: package test"
    command:
      - npm publish --access public --dry-run
  - label: ":rocket: Build"
    if: build.branch == "master"
    command:
      - npm publish ../regime_js --access public --dry-run
