steps:
  - label: ":hammmer: Test"
    command:
      - npm install
      - npm test
  - label: ":rocket: Build"
    if: build.pull_request.master
    command:
      - npm publish ../regime_js/ --access public --dry-run
