steps:
  - label: ":hammmer: Test"
    command:
      - npm install
      - npm test
      - ls
  - label: ":rocket: Build"
    if: build.branch == "master"
    command:
      - npm publish ../regime_js/ --access public --dry-run
